---
- hosts: all
  become: yes
  vars:
    mysql_root_password: "NewPassword123$"
    mysql_users:
      - name: MasterDba
        host: "localhost"
        password: "MasterDba123$"
        priv: "*.*:ALL,GRANT"


  tasks:
  - name: download and install Mysql 8 Repo 
    yum:
       name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
       state: present
  
  - name: delete mariadb libs
    yum:
      name: mariadb-libs
      state: removed
  
  - name: install mysql 8
    yum:
      name: ['mysql-community-devel*', 'mysql-community-server*', 'MySQL-python']
      state: present
  
  - name: copy simple my.cnf
    copy:
      src: ./my.cnf
      dest: /etc/my.cnf
      mode: 0644
  
  - name: enable mysql
    systemd:
      name: mysqld
      state: restarted
      enabled: yes

  - name: get root password
    shell: "grep 'A temporary password is generated for root@localhost' /var/lib/mysql/mysql-error.log | awk -F ' ' '{print $(NF)}'"
    register: root_password
  
  - debug:
     msg:  "temp password: {{ root_password.stdout_lines[0] }}"

  - name: update expired root user password
    command: mysql --user root --password={{ root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
  
  - name: Ensure MySQL users are present.
    mysql_user:
      login_user: 'root'
      login_password: '{{ mysql_root_password }}'
      name: '{{ item.name }}'
      host: "{{ item.host | default('localhost') }}"
      password: "{{ item.password }}"
      priv: "{{ item.priv | default('*.*:USAGE') }}"
      state: "present"
      append_privs: "no"
      encrypted: "no"
    with_items: "{{ mysql_users }}"
    #no_log: true
